name: chores
on:
  workflow_call:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  # PR 作成者を assignee に追加する
  assign:
    name: Auto Assign
    if: github.actor != 'dependabot[bot]' && (github.event.action == 'opened' || github.event.action == 'ready_for_review')
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-assignee ${{ github.event.pull_request.user.login }}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        if: ${{ toJSON(github.event.pull_request.assignees) == '[]' }}

