name: Code Analysis
on:
  workflow_call:

jobs:

  # biome を reviewdog で実行
  # https://biomejs.dev/
  # https://github.com/mongolyy/reviewdog-action-biome
  biome:
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: mongolyy/reviewdog-action-biome@c49bee54c1f87e4be32446ae3deca3a186b88a3a # v2.11.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: error # エラーレベルがあれば失敗. エラー以外は成功でコメントを残す

  # typos を reviewdog で実行
  # https://github.com/crate-ci/typos
  # https://github.com/reviewdog/action-typos
  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: reviewdog/action-typos@d5eb1bbcd1b3bfde596f6eeb470322727862fe98 # v1.19.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: error # エラーレベルがあれば失敗. エラー以外は成功でコメントを残す

  # gitleak を reviewdog で実行
  # https://github.com/gitleaks/gitleaks
  # https://github.com/reviewdog/action-gitleaks
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: reviewdog/action-gitleaks@2b7b5685e3e3eecddab5d30cfa04f18123031421 # v1.8.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: error # エラーレベルがあれば失敗. エラー以外は成功でコメントを残す

